### ISSUE TITLE
Makin Login Functional

### ISSUE THREAD

**Issue by kirti281003** [SnowScriptWinterOfCode/ChefBook#5]
Use Auth0 to make login section functional

**Comment by acecoder7** [comment]
i would like to work on this. Pls assign

**Comment by acecoder7** [comment]
i would like to make signup/login functionality using firebase. Kindly assign @i-am-SnehaChauhan @Nitya-Pasrija

**Comment by i-am-SnehaChauhan** [comment]
Hey @acecoder7 actually we want to make Login Functionality using Auth0. Would u like to do that?

**Comment by acecoder7** [comment]
> Hey @acecoder7 actually we want to make Login Functionality using Auth0. Would u like to do that?

yes sure

**Comment by i-am-SnehaChauhan** [comment]
@acecoder7 ok then i am assigning this to u.

**Comment by acecoder7** [comment]
I have raised the PR, kindly review @i-am-SnehaChauhan 

Here is the demo of login functionality with auth0 as required

https://drive.google.com/file/d/1df1thUMIS58Q1zu7p5v-19oxzBJBfxwK/view?usp=drive_link
(since file size exceeds hence uploaded on drive)

Highlighting the features added in this PR under issue- #5 
- A working login and signup using [Auth0](https://auth0.com/)
- login and signup via google and email/password is enabled
- A customized login/signup interface
- necessary changes in navbar ( adding login/logout/profile dropdown)
- a simple and clean profile page showing profile image, user name, user email.
- logout functional
- a basic frontend routing along with organizing the code in different folders and files as per the requirements of this issue


Additionally adding ss of few pages for easy reference
![Screenshot (528)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/12ecfa84-28c2-4670-ab91-a79d9a41874c)
![Screenshot (529)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/4b555ad8-930e-4d27-93c1-5ced7262cfa6)
![Screenshot (530)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/032e8216-063b-4b27-85c4-c8ef94ff875f)


Kindly let me any other changes are needed under this issue
